[New I/O  worker #3] 11:15:15,795 SEVERE [deployment-8c25d1bf-7714-4f01-b4a6-492fc66d542e-0]  Exception in Java verticle script
org.jboss.netty.channel.ChannelException: Failed to bind to: localhost/127.0.0.1:8080
	at org.jboss.netty.bootstrap.ServerBootstrap.bind(ServerBootstrap.java:298)
	at org.vertx.java.core.http.impl.DefaultHttpServer.listen(DefaultHttpServer.java:210)
	at com.google.collide.server.fe.WebFE.start(WebFE.java:98)
	at org.vertx.java.deploy.impl.VerticleManager$2.run(VerticleManager.java:288)
	at org.vertx.java.core.impl.Context$2.run(Context.java:119)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.processEventQueue(AbstractNioWorker.java:360)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:244)
	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:38)
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:102)
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
	at java.lang.Thread.run(Thread.java:722)
Caused by: java.net.BindException: Address already in use
	at sun.nio.ch.Net.bind0(Native Method)
	at sun.nio.ch.Net.bind(Net.java:344)
	at sun.nio.ch.Net.bind(Net.java:336)
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:199)
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
	at org.jboss.netty.channel.socket.nio.NioServerSocketPipelineSink.bind(NioServerSocketPipelineSink.java:138)
	at org.jboss.netty.channel.socket.nio.NioServerSocketPipelineSink.handleServerSocket(NioServerSocketPipelineSink.java:90)
	at org.jboss.netty.channel.socket.nio.NioServerSocketPipelineSink.eventSunk(NioServerSocketPipelineSink.java:64)
	at org.jboss.netty.channel.Channels.bind(Channels.java:569)
	at org.jboss.netty.channel.AbstractChannel.bind(AbstractChannel.java:186)
	at org.jboss.netty.bootstrap.ServerBootstrap$Binder.channelOpen(ServerBootstrap.java:343)
	at org.jboss.netty.channel.Channels.fireChannelOpen(Channels.java:170)
	at org.jboss.netty.channel.socket.nio.NioServerSocketChannel.<init>(NioServerSocketChannel.java:80)
	at org.jboss.netty.channel.socket.nio.NioServerSocketChannelFactory.newChannel(NioServerSocketChannelFactory.java:156)
	at org.jboss.netty.channel.socket.nio.NioServerSocketChannelFactory.newChannel(NioServerSocketChannelFactory.java:86)
	at org.jboss.netty.bootstrap.ServerBootstrap.bind(ServerBootstrap.java:277)
	at org.vertx.java.core.http.impl.DefaultHttpServer.listen(DefaultHttpServer.java:210)
	at com.google.collide.server.fe.WebFE.start(WebFE.java:98)
	at org.vertx.java.deploy.impl.VerticleManager$2.run(VerticleManager.java:288)
	at org.vertx.java.core.impl.Context$2.run(Context.java:119)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.processEventQueue(AbstractNioWorker.java:360)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:244)
	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:38)
	... 3 more
[New I/O  worker #7] 11:15:15,794 SEVERE [deployment-8c25d1bf-7714-4f01-b4a6-492fc66d542e-4]  Exception in Java verticle script
org.jboss.netty.channel.ChannelException: Failed to bind to: localhost/127.0.0.1:8080
	at org.jboss.netty.bootstrap.ServerBootstrap.bind(ServerBootstrap.java:298)
	at org.vertx.java.core.http.impl.DefaultHttpServer.listen(DefaultHttpServer.java:210)
	at com.google.collide.server.fe.WebFE.start(WebFE.java:98)
	at org.vertx.java.deploy.impl.VerticleManager$2.run(VerticleManager.java:288)
	at org.vertx.java.core.impl.Context$2.run(Context.java:119)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.processEventQueue(AbstractNioWorker.java:360)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:244)
	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:38)
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:102)
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
	at java.lang.Thread.run(Thread.java:722)
Caused by: java.net.BindException: Address already in use
	at sun.nio.ch.Net.bind0(Native Method)
	at sun.nio.ch.Net.bind(Net.java:344)
	at sun.nio.ch.Net.bind(Net.java:336)
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:199)
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
	at org.jboss.netty.channel.socket.nio.NioServerSocketPipelineSink.bind(NioServerSocketPipelineSink.java:138)
	at org.jboss.netty.channel.socket.nio.NioServerSocketPipelineSink.handleServerSocket(NioServerSocketPipelineSink.java:90)
	at org.jboss.netty.channel.socket.nio.NioServerSocketPipelineSink.eventSunk(NioServerSocketPipelineSink.java:64)
	at org.jboss.netty.channel.Channels.bind(Channels.java:569)
	at org.jboss.netty.channel.AbstractChannel.bind(AbstractChannel.java:186)
	at org.jboss.netty.bootstrap.ServerBootstrap$Binder.channelOpen(ServerBootstrap.java:343)
	at org.jboss.netty.channel.Channels.fireChannelOpen(Channels.java:170)
	at org.jboss.netty.channel.socket.nio.NioServerSocketChannel.<init>(NioServerSocketChannel.java:80)
	at org.jboss.netty.channel.socket.nio.NioServerSocketChannelFactory.newChannel(NioServerSocketChannelFactory.java:156)
	at org.jboss.netty.channel.socket.nio.NioServerSocketChannelFactory.newChannel(NioServerSocketChannelFactory.java:86)
	at org.jboss.netty.bootstrap.ServerBootstrap.bind(ServerBootstrap.java:277)
	at org.vertx.java.core.http.impl.DefaultHttpServer.listen(DefaultHttpServer.java:210)
	at com.google.collide.server.fe.WebFE.start(WebFE.java:98)
	at org.vertx.java.deploy.impl.VerticleManager$2.run(VerticleManager.java:288)
	at org.vertx.java.core.impl.Context$2.run(Context.java:119)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.processEventQueue(AbstractNioWorker.java:360)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:244)
	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:38)
	... 3 more
[New I/O  worker #8] 11:15:15,790 SEVERE [deployment-8c25d1bf-7714-4f01-b4a6-492fc66d542e-5]  Exception in Java verticle script
org.jboss.netty.channel.ChannelException: Failed to bind to: localhost/127.0.0.1:8080
	at org.jboss.netty.bootstrap.ServerBootstrap.bind(ServerBootstrap.java:298)
	at org.vertx.java.core.http.impl.DefaultHttpServer.listen(DefaultHttpServer.java:210)
	at com.google.collide.server.fe.WebFE.start(WebFE.java:98)
	at org.vertx.java.deploy.impl.VerticleManager$2.run(VerticleManager.java:288)
	at org.vertx.java.core.impl.Context$2.run(Context.java:119)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.processEventQueue(AbstractNioWorker.java:360)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:244)
	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:38)
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:102)
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
	at java.lang.Thread.run(Thread.java:722)
Caused by: java.net.BindException: Address already in use
	at sun.nio.ch.Net.bind0(Native Method)
	at sun.nio.ch.Net.bind(Net.java:344)
	at sun.nio.ch.Net.bind(Net.java:336)
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:199)
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
	at org.jboss.netty.channel.socket.nio.NioServerSocketPipelineSink.bind(NioServerSocketPipelineSink.java:138)
	at org.jboss.netty.channel.socket.nio.NioServerSocketPipelineSink.handleServerSocket(NioServerSocketPipelineSink.java:90)
	at org.jboss.netty.channel.socket.nio.NioServerSocketPipelineSink.eventSunk(NioServerSocketPipelineSink.java:64)
	at org.jboss.netty.channel.Channels.bind(Channels.java:569)
	at org.jboss.netty.channel.AbstractChannel.bind(AbstractChannel.java:186)
	at org.jboss.netty.bootstrap.ServerBootstrap$Binder.channelOpen(ServerBootstrap.java:343)
	at org.jboss.netty.channel.Channels.fireChannelOpen(Channels.java:170)
	at org.jboss.netty.channel.socket.nio.NioServerSocketChannel.<init>(NioServerSocketChannel.java:80)
	at org.jboss.netty.channel.socket.nio.NioServerSocketChannelFactory.newChannel(NioServerSocketChannelFactory.java:156)
	at org.jboss.netty.channel.socket.nio.NioServerSocketChannelFactory.newChannel(NioServerSocketChannelFactory.java:86)
	at org.jboss.netty.bootstrap.ServerBootstrap.bind(ServerBootstrap.java:277)
	at org.vertx.java.core.http.impl.DefaultHttpServer.listen(DefaultHttpServer.java:210)
	at com.google.collide.server.fe.WebFE.start(WebFE.java:98)
	at org.vertx.java.deploy.impl.VerticleManager$2.run(VerticleManager.java:288)
	at org.vertx.java.core.impl.Context$2.run(Context.java:119)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.processEventQueue(AbstractNioWorker.java:360)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:244)
	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:38)
	... 3 more
[New I/O  worker #6] 11:15:15,791 SEVERE [deployment-8c25d1bf-7714-4f01-b4a6-492fc66d542e-2]  Exception in Java verticle script
org.jboss.netty.channel.ChannelException: Failed to bind to: localhost/127.0.0.1:8080
	at org.jboss.netty.bootstrap.ServerBootstrap.bind(ServerBootstrap.java:298)
	at org.vertx.java.core.http.impl.DefaultHttpServer.listen(DefaultHttpServer.java:210)
	at com.google.collide.server.fe.WebFE.start(WebFE.java:98)
	at org.vertx.java.deploy.impl.VerticleManager$2.run(VerticleManager.java:288)
	at org.vertx.java.core.impl.Context$2.run(Context.java:119)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.processEventQueue(AbstractNioWorker.java:360)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:244)
	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:38)
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:102)
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
	at java.lang.Thread.run(Thread.java:722)
Caused by: java.net.BindException: Address already in use
	at sun.nio.ch.Net.bind0(Native Method)
	at sun.nio.ch.Net.bind(Net.java:344)
	at sun.nio.ch.Net.bind(Net.java:336)
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:199)
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
	at org.jboss.netty.channel.socket.nio.NioServerSocketPipelineSink.bind(NioServerSocketPipelineSink.java:138)
	at org.jboss.netty.channel.socket.nio.NioServerSocketPipelineSink.handleServerSocket(NioServerSocketPipelineSink.java:90)
	at org.jboss.netty.channel.socket.nio.NioServerSocketPipelineSink.eventSunk(NioServerSocketPipelineSink.java:64)
	at org.jboss.netty.channel.Channels.bind(Channels.java:569)
	at org.jboss.netty.channel.AbstractChannel.bind(AbstractChannel.java:186)
	at org.jboss.netty.bootstrap.ServerBootstrap$Binder.channelOpen(ServerBootstrap.java:343)
	at org.jboss.netty.channel.Channels.fireChannelOpen(Channels.java:170)
	at org.jboss.netty.channel.socket.nio.NioServerSocketChannel.<init>(NioServerSocketChannel.java:80)
	at org.jboss.netty.channel.socket.nio.NioServerSocketChannelFactory.newChannel(NioServerSocketChannelFactory.java:156)
	at org.jboss.netty.channel.socket.nio.NioServerSocketChannelFactory.newChannel(NioServerSocketChannelFactory.java:86)
	at org.jboss.netty.bootstrap.ServerBootstrap.bind(ServerBootstrap.java:277)
	at org.vertx.java.core.http.impl.DefaultHttpServer.listen(DefaultHttpServer.java:210)
	at com.google.collide.server.fe.WebFE.start(WebFE.java:98)
	at org.vertx.java.deploy.impl.VerticleManager$2.run(VerticleManager.java:288)
	at org.vertx.java.core.impl.Context$2.run(Context.java:119)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.processEventQueue(AbstractNioWorker.java:360)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:244)
	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:38)
	... 3 more
[New I/O  worker #1] 11:15:15,792 SEVERE [deployment-8c25d1bf-7714-4f01-b4a6-492fc66d542e-6]  Exception in Java verticle script
org.jboss.netty.channel.ChannelException: Failed to bind to: localhost/127.0.0.1:8080
	at org.jboss.netty.bootstrap.ServerBootstrap.bind(ServerBootstrap.java:298)
	at org.vertx.java.core.http.impl.DefaultHttpServer.listen(DefaultHttpServer.java:210)
	at com.google.collide.server.fe.WebFE.start(WebFE.java:98)
	at org.vertx.java.deploy.impl.VerticleManager$2.run(VerticleManager.java:288)
	at org.vertx.java.core.impl.Context$2.run(Context.java:119)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.processEventQueue(AbstractNioWorker.java:360)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:244)
	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:38)
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:102)
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
	at java.lang.Thread.run(Thread.java:722)
Caused by: java.net.BindException: Address already in use
	at sun.nio.ch.Net.bind0(Native Method)
	at sun.nio.ch.Net.bind(Net.java:344)
	at sun.nio.ch.Net.bind(Net.java:336)
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:199)
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
	at org.jboss.netty.channel.socket.nio.NioServerSocketPipelineSink.bind(NioServerSocketPipelineSink.java:138)
	at org.jboss.netty.channel.socket.nio.NioServerSocketPipelineSink.handleServerSocket(NioServerSocketPipelineSink.java:90)
	at org.jboss.netty.channel.socket.nio.NioServerSocketPipelineSink.eventSunk(NioServerSocketPipelineSink.java:64)
	at org.jboss.netty.channel.Channels.bind(Channels.java:569)
	at org.jboss.netty.channel.AbstractChannel.bind(AbstractChannel.java:186)
	at org.jboss.netty.bootstrap.ServerBootstrap$Binder.channelOpen(ServerBootstrap.java:343)
	at org.jboss.netty.channel.Channels.fireChannelOpen(Channels.java:170)
	at org.jboss.netty.channel.socket.nio.NioServerSocketChannel.<init>(NioServerSocketChannel.java:80)
	at org.jboss.netty.channel.socket.nio.NioServerSocketChannelFactory.newChannel(NioServerSocketChannelFactory.java:156)
	at org.jboss.netty.channel.socket.nio.NioServerSocketChannelFactory.newChannel(NioServerSocketChannelFactory.java:86)
	at org.jboss.netty.bootstrap.ServerBootstrap.bind(ServerBootstrap.java:277)
	at org.vertx.java.core.http.impl.DefaultHttpServer.listen(DefaultHttpServer.java:210)
	at com.google.collide.server.fe.WebFE.start(WebFE.java:98)
	at org.vertx.java.deploy.impl.VerticleManager$2.run(VerticleManager.java:288)
	at org.vertx.java.core.impl.Context$2.run(Context.java:119)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.processEventQueue(AbstractNioWorker.java:360)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:244)
	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:38)
	... 3 more
[New I/O  worker #5] 11:15:15,793 SEVERE [deployment-8c25d1bf-7714-4f01-b4a6-492fc66d542e-3]  Exception in Java verticle script
org.jboss.netty.channel.ChannelException: Failed to bind to: localhost/127.0.0.1:8080
	at org.jboss.netty.bootstrap.ServerBootstrap.bind(ServerBootstrap.java:298)
	at org.vertx.java.core.http.impl.DefaultHttpServer.listen(DefaultHttpServer.java:210)
	at com.google.collide.server.fe.WebFE.start(WebFE.java:98)
	at org.vertx.java.deploy.impl.VerticleManager$2.run(VerticleManager.java:288)
	at org.vertx.java.core.impl.Context$2.run(Context.java:119)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.processEventQueue(AbstractNioWorker.java:360)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:244)
	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:38)
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:102)
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
	at java.lang.Thread.run(Thread.java:722)
Caused by: java.net.BindException: Address already in use
	at sun.nio.ch.Net.bind0(Native Method)
	at sun.nio.ch.Net.bind(Net.java:344)
	at sun.nio.ch.Net.bind(Net.java:336)
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:199)
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
	at org.jboss.netty.channel.socket.nio.NioServerSocketPipelineSink.bind(NioServerSocketPipelineSink.java:138)
	at org.jboss.netty.channel.socket.nio.NioServerSocketPipelineSink.handleServerSocket(NioServerSocketPipelineSink.java:90)
	at org.jboss.netty.channel.socket.nio.NioServerSocketPipelineSink.eventSunk(NioServerSocketPipelineSink.java:64)
	at org.jboss.netty.channel.Channels.bind(Channels.java:569)
	at org.jboss.netty.channel.AbstractChannel.bind(AbstractChannel.java:186)
	at org.jboss.netty.bootstrap.ServerBootstrap$Binder.channelOpen(ServerBootstrap.java:343)
	at org.jboss.netty.channel.Channels.fireChannelOpen(Channels.java:170)
	at org.jboss.netty.channel.socket.nio.NioServerSocketChannel.<init>(NioServerSocketChannel.java:80)
	at org.jboss.netty.channel.socket.nio.NioServerSocketChannelFactory.newChannel(NioServerSocketChannelFactory.java:156)
	at org.jboss.netty.channel.socket.nio.NioServerSocketChannelFactory.newChannel(NioServerSocketChannelFactory.java:86)
	at org.jboss.netty.bootstrap.ServerBootstrap.bind(ServerBootstrap.java:277)
	at org.vertx.java.core.http.impl.DefaultHttpServer.listen(DefaultHttpServer.java:210)
	at com.google.collide.server.fe.WebFE.start(WebFE.java:98)
	at org.vertx.java.deploy.impl.VerticleManager$2.run(VerticleManager.java:288)
	at org.vertx.java.core.impl.Context$2.run(Context.java:119)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.processEventQueue(AbstractNioWorker.java:360)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:244)
	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:38)
	... 3 more
[New I/O  worker #4] 11:15:15,794 SEVERE [deployment-8c25d1bf-7714-4f01-b4a6-492fc66d542e-1]  Exception in Java verticle script
org.jboss.netty.channel.ChannelException: Failed to bind to: localhost/127.0.0.1:8080
	at org.jboss.netty.bootstrap.ServerBootstrap.bind(ServerBootstrap.java:298)
	at org.vertx.java.core.http.impl.DefaultHttpServer.listen(DefaultHttpServer.java:210)
	at com.google.collide.server.fe.WebFE.start(WebFE.java:98)
	at org.vertx.java.deploy.impl.VerticleManager$2.run(VerticleManager.java:288)
	at org.vertx.java.core.impl.Context$2.run(Context.java:119)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.processEventQueue(AbstractNioWorker.java:360)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:244)
	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:38)
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:102)
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
	at java.lang.Thread.run(Thread.java:722)
Caused by: java.net.BindException: Address already in use
	at sun.nio.ch.Net.bind0(Native Method)
	at sun.nio.ch.Net.bind(Net.java:344)
	at sun.nio.ch.Net.bind(Net.java:336)
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:199)
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
	at org.jboss.netty.channel.socket.nio.NioServerSocketPipelineSink.bind(NioServerSocketPipelineSink.java:138)
	at org.jboss.netty.channel.socket.nio.NioServerSocketPipelineSink.handleServerSocket(NioServerSocketPipelineSink.java:90)
	at org.jboss.netty.channel.socket.nio.NioServerSocketPipelineSink.eventSunk(NioServerSocketPipelineSink.java:64)
	at org.jboss.netty.channel.Channels.bind(Channels.java:569)
	at org.jboss.netty.channel.AbstractChannel.bind(AbstractChannel.java:186)
	at org.jboss.netty.bootstrap.ServerBootstrap$Binder.channelOpen(ServerBootstrap.java:343)
	at org.jboss.netty.channel.Channels.fireChannelOpen(Channels.java:170)
	at org.jboss.netty.channel.socket.nio.NioServerSocketChannel.<init>(NioServerSocketChannel.java:80)
	at org.jboss.netty.channel.socket.nio.NioServerSocketChannelFactory.newChannel(NioServerSocketChannelFactory.java:156)
	at org.jboss.netty.channel.socket.nio.NioServerSocketChannelFactory.newChannel(NioServerSocketChannelFactory.java:86)
	at org.jboss.netty.bootstrap.ServerBootstrap.bind(ServerBootstrap.java:277)
	at org.vertx.java.core.http.impl.DefaultHttpServer.listen(DefaultHttpServer.java:210)
	at com.google.collide.server.fe.WebFE.start(WebFE.java:98)
	at org.vertx.java.deploy.impl.VerticleManager$2.run(VerticleManager.java:288)
	at org.vertx.java.core.impl.Context$2.run(Context.java:119)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.processEventQueue(AbstractNioWorker.java:360)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:244)
	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:38)
	... 3 more
[New I/O  worker #5] 11:15:15,826 SEVERE [deployment-8c25d1bf-7714-4f01-b4a6-492fc66d542e-3]  Exception in Java verticle script
java.lang.NullPointerException
	at org.vertx.java.deploy.impl.VerticleManager.doUndeploy(VerticleManager.java:411)
	at org.vertx.java.deploy.impl.VerticleManager.doUndeploy(VerticleManager.java:400)
	at org.vertx.java.deploy.impl.VerticleManager.access$400(VerticleManager.java:50)
	at org.vertx.java.deploy.impl.VerticleManager$2.run(VerticleManager.java:291)
	at org.vertx.java.core.impl.Context$2.run(Context.java:119)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.processEventQueue(AbstractNioWorker.java:360)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:244)
	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:38)
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:102)
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
	at java.lang.Thread.run(Thread.java:722)
[New I/O  worker #4] 11:15:15,827 SEVERE [deployment-8c25d1bf-7714-4f01-b4a6-492fc66d542e-1]  Exception in Java verticle script
java.lang.NullPointerException
	at org.vertx.java.deploy.impl.VerticleManager.doUndeploy(VerticleManager.java:411)
	at org.vertx.java.deploy.impl.VerticleManager.doUndeploy(VerticleManager.java:400)
	at org.vertx.java.deploy.impl.VerticleManager.access$400(VerticleManager.java:50)
	at org.vertx.java.deploy.impl.VerticleManager$2.run(VerticleManager.java:291)
	at org.vertx.java.core.impl.Context$2.run(Context.java:119)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.processEventQueue(AbstractNioWorker.java:360)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:244)
	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:38)
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:102)
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
	at java.lang.Thread.run(Thread.java:722)
[New I/O  worker #6] 11:15:15,815 SEVERE [deployment-8c25d1bf-7714-4f01-b4a6-492fc66d542e-2]  Exception in Java verticle script
java.lang.NullPointerException
	at org.vertx.java.deploy.impl.VerticleManager.doUndeploy(VerticleManager.java:411)
	at org.vertx.java.deploy.impl.VerticleManager.doUndeploy(VerticleManager.java:400)
	at org.vertx.java.deploy.impl.VerticleManager.access$400(VerticleManager.java:50)
	at org.vertx.java.deploy.impl.VerticleManager$2.run(VerticleManager.java:291)
	at org.vertx.java.core.impl.Context$2.run(Context.java:119)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.processEventQueue(AbstractNioWorker.java:360)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:244)
	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:38)
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:102)
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
	at java.lang.Thread.run(Thread.java:722)
[New I/O  worker #3] 11:15:15,810 SEVERE [deployment-8c25d1bf-7714-4f01-b4a6-492fc66d542e-8]  Exception in Java verticle script
org.jboss.netty.channel.ChannelException: Failed to bind to: localhost/127.0.0.1:8080
	at org.jboss.netty.bootstrap.ServerBootstrap.bind(ServerBootstrap.java:298)
	at org.vertx.java.core.http.impl.DefaultHttpServer.listen(DefaultHttpServer.java:210)
	at com.google.collide.server.fe.WebFE.start(WebFE.java:98)
	at org.vertx.java.deploy.impl.VerticleManager$2.run(VerticleManager.java:288)
	at org.vertx.java.core.impl.Context$2.run(Context.java:119)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.processEventQueue(AbstractNioWorker.java:360)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:244)
	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:38)
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:102)
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
	at java.lang.Thread.run(Thread.java:722)
Caused by: java.net.BindException: Address already in use
	at sun.nio.ch.Net.bind0(Native Method)
	at sun.nio.ch.Net.bind(Net.java:344)
	at sun.nio.ch.Net.bind(Net.java:336)
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:199)
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
	at org.jboss.netty.channel.socket.nio.NioServerSocketPipelineSink.bind(NioServerSocketPipelineSink.java:138)
	at org.jboss.netty.channel.socket.nio.NioServerSocketPipelineSink.handleServerSocket(NioServerSocketPipelineSink.java:90)
	at org.jboss.netty.channel.socket.nio.NioServerSocketPipelineSink.eventSunk(NioServerSocketPipelineSink.java:64)
	at org.jboss.netty.channel.Channels.bind(Channels.java:569)
	at org.jboss.netty.channel.AbstractChannel.bind(AbstractChannel.java:186)
	at org.jboss.netty.bootstrap.ServerBootstrap$Binder.channelOpen(ServerBootstrap.java:343)
	at org.jboss.netty.channel.Channels.fireChannelOpen(Channels.java:170)
	at org.jboss.netty.channel.socket.nio.NioServerSocketChannel.<init>(NioServerSocketChannel.java:80)
	at org.jboss.netty.channel.socket.nio.NioServerSocketChannelFactory.newChannel(NioServerSocketChannelFactory.java:156)
	at org.jboss.netty.channel.socket.nio.NioServerSocketChannelFactory.newChannel(NioServerSocketChannelFactory.java:86)
	at org.jboss.netty.bootstrap.ServerBootstrap.bind(ServerBootstrap.java:277)
	at org.vertx.java.core.http.impl.DefaultHttpServer.listen(DefaultHttpServer.java:210)
	at com.google.collide.server.fe.WebFE.start(WebFE.java:98)
	at org.vertx.java.deploy.impl.VerticleManager$2.run(VerticleManager.java:288)
	at org.vertx.java.core.impl.Context$2.run(Context.java:119)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.processEventQueue(AbstractNioWorker.java:360)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:244)
	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:38)
	... 3 more
[New I/O  worker #8] 11:15:15,806 SEVERE [deployment-8c25d1bf-7714-4f01-b4a6-492fc66d542e-5]  Exception in Java verticle script
java.lang.NullPointerException
	at org.vertx.java.deploy.impl.VerticleManager.doUndeploy(VerticleManager.java:411)
	at org.vertx.java.deploy.impl.VerticleManager.doUndeploy(VerticleManager.java:400)
	at org.vertx.java.deploy.impl.VerticleManager.access$400(VerticleManager.java:50)
	at org.vertx.java.deploy.impl.VerticleManager$2.run(VerticleManager.java:291)
	at org.vertx.java.core.impl.Context$2.run(Context.java:119)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.processEventQueue(AbstractNioWorker.java:360)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:244)
	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:38)
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:102)
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
	at java.lang.Thread.run(Thread.java:722)
[New I/O  worker #7] 11:15:15,805 SEVERE [deployment-8c25d1bf-7714-4f01-b4a6-492fc66d542e-4]  Exception in Java verticle script
java.lang.NullPointerException
	at org.vertx.java.deploy.impl.VerticleManager.doUndeploy(VerticleManager.java:411)
	at org.vertx.java.deploy.impl.VerticleManager.doUndeploy(VerticleManager.java:400)
	at org.vertx.java.deploy.impl.VerticleManager.access$400(VerticleManager.java:50)
	at org.vertx.java.deploy.impl.VerticleManager$2.run(VerticleManager.java:291)
	at org.vertx.java.core.impl.Context$2.run(Context.java:119)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.processEventQueue(AbstractNioWorker.java:360)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:244)
	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:38)
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:102)
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
	at java.lang.Thread.run(Thread.java:722)
[New I/O  worker #2] 11:15:15,789 SEVERE [deployment-8c25d1bf-7714-4f01-b4a6-492fc66d542e-7]  Exception in Java verticle script
org.jboss.netty.channel.ChannelException: Failed to bind to: localhost/127.0.0.1:8080
	at org.jboss.netty.bootstrap.ServerBootstrap.bind(ServerBootstrap.java:298)
	at org.vertx.java.core.http.impl.DefaultHttpServer.listen(DefaultHttpServer.java:210)
	at com.google.collide.server.fe.WebFE.start(WebFE.java:98)
	at org.vertx.java.deploy.impl.VerticleManager$2.run(VerticleManager.java:288)
	at org.vertx.java.core.impl.Context$2.run(Context.java:119)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.processEventQueue(AbstractNioWorker.java:360)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:244)
	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:38)
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:102)
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
	at java.lang.Thread.run(Thread.java:722)
Caused by: java.net.BindException: Address already in use
	at sun.nio.ch.Net.bind0(Native Method)
	at sun.nio.ch.Net.bind(Net.java:344)
	at sun.nio.ch.Net.bind(Net.java:336)
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:199)
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
	at org.jboss.netty.channel.socket.nio.NioServerSocketPipelineSink.bind(NioServerSocketPipelineSink.java:138)
	at org.jboss.netty.channel.socket.nio.NioServerSocketPipelineSink.handleServerSocket(NioServerSocketPipelineSink.java:90)
	at org.jboss.netty.channel.socket.nio.NioServerSocketPipelineSink.eventSunk(NioServerSocketPipelineSink.java:64)
	at org.jboss.netty.channel.Channels.bind(Channels.java:569)
	at org.jboss.netty.channel.AbstractChannel.bind(AbstractChannel.java:186)
	at org.jboss.netty.bootstrap.ServerBootstrap$Binder.channelOpen(ServerBootstrap.java:343)
	at org.jboss.netty.channel.Channels.fireChannelOpen(Channels.java:170)
	at org.jboss.netty.channel.socket.nio.NioServerSocketChannel.<init>(NioServerSocketChannel.java:80)
	at org.jboss.netty.channel.socket.nio.NioServerSocketChannelFactory.newChannel(NioServerSocketChannelFactory.java:156)
	at org.jboss.netty.channel.socket.nio.NioServerSocketChannelFactory.newChannel(NioServerSocketChannelFactory.java:86)
	at org.jboss.netty.bootstrap.ServerBootstrap.bind(ServerBootstrap.java:277)
	at org.vertx.java.core.http.impl.DefaultHttpServer.listen(DefaultHttpServer.java:210)
	at com.google.collide.server.fe.WebFE.start(WebFE.java:98)
	at org.vertx.java.deploy.impl.VerticleManager$2.run(VerticleManager.java:288)
	at org.vertx.java.core.impl.Context$2.run(Context.java:119)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.processEventQueue(AbstractNioWorker.java:360)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:244)
	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:38)
	... 3 more
[New I/O  worker #4] 11:15:15,839 SEVERE [deployment-8c25d1bf-7714-4f01-b4a6-492fc66d542e-9]  Exception in Java verticle script
org.jboss.netty.channel.ChannelException: Failed to bind to: localhost/127.0.0.1:8080
	at org.jboss.netty.bootstrap.ServerBootstrap.bind(ServerBootstrap.java:298)
	at org.vertx.java.core.http.impl.DefaultHttpServer.listen(DefaultHttpServer.java:210)
	at com.google.collide.server.fe.WebFE.start(WebFE.java:98)
	at org.vertx.java.deploy.impl.VerticleManager$2.run(VerticleManager.java:288)
	at org.vertx.java.core.impl.Context$2.run(Context.java:119)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.processEventQueue(AbstractNioWorker.java:360)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:244)
	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:38)
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:102)
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
	at java.lang.Thread.run(Thread.java:722)
Caused by: java.net.BindException: Address already in use
	at sun.nio.ch.Net.bind0(Native Method)
	at sun.nio.ch.Net.bind(Net.java:344)
	at sun.nio.ch.Net.bind(Net.java:336)
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:199)
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
	at org.jboss.netty.channel.socket.nio.NioServerSocketPipelineSink.bind(NioServerSocketPipelineSink.java:138)
	at org.jboss.netty.channel.socket.nio.NioServerSocketPipelineSink.handleServerSocket(NioServerSocketPipelineSink.java:90)
	at org.jboss.netty.channel.socket.nio.NioServerSocketPipelineSink.eventSunk(NioServerSocketPipelineSink.java:64)
	at org.jboss.netty.channel.Channels.bind(Channels.java:569)
	at org.jboss.netty.channel.AbstractChannel.bind(AbstractChannel.java:186)
	at org.jboss.netty.bootstrap.ServerBootstrap$Binder.channelOpen(ServerBootstrap.java:343)
	at org.jboss.netty.channel.Channels.fireChannelOpen(Channels.java:170)
	at org.jboss.netty.channel.socket.nio.NioServerSocketChannel.<init>(NioServerSocketChannel.java:80)
	at org.jboss.netty.channel.socket.nio.NioServerSocketChannelFactory.newChannel(NioServerSocketChannelFactory.java:156)
	at org.jboss.netty.channel.socket.nio.NioServerSocketChannelFactory.newChannel(NioServerSocketChannelFactory.java:86)
	at org.jboss.netty.bootstrap.ServerBootstrap.bind(ServerBootstrap.java:277)
	at org.vertx.java.core.http.impl.DefaultHttpServer.listen(DefaultHttpServer.java:210)
	at com.google.collide.server.fe.WebFE.start(WebFE.java:98)
	at org.vertx.java.deploy.impl.VerticleManager$2.run(VerticleManager.java:288)
	at org.vertx.java.core.impl.Context$2.run(Context.java:119)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.processEventQueue(AbstractNioWorker.java:360)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:244)
	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:38)
	... 3 more
[New I/O  worker #4] 11:15:15,849 SEVERE [deployment-8c25d1bf-7714-4f01-b4a6-492fc66d542e-9]  Exception in Java verticle script
java.lang.NullPointerException
	at org.vertx.java.deploy.impl.VerticleManager.doUndeploy(VerticleManager.java:411)
	at org.vertx.java.deploy.impl.VerticleManager.doUndeploy(VerticleManager.java:400)
	at org.vertx.java.deploy.impl.VerticleManager.access$400(VerticleManager.java:50)
	at org.vertx.java.deploy.impl.VerticleManager$2.run(VerticleManager.java:291)
	at org.vertx.java.core.impl.Context$2.run(Context.java:119)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.processEventQueue(AbstractNioWorker.java:360)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:244)
	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:38)
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:102)
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
	at java.lang.Thread.run(Thread.java:722)
[New I/O  worker #1] 11:15:15,816 SEVERE [deployment-8c25d1bf-7714-4f01-b4a6-492fc66d542e-6]  Exception in Java verticle script
java.lang.NullPointerException
	at org.vertx.java.deploy.impl.VerticleManager.doUndeploy(VerticleManager.java:411)
	at org.vertx.java.deploy.impl.VerticleManager.doUndeploy(VerticleManager.java:400)
	at org.vertx.java.deploy.impl.VerticleManager.access$400(VerticleManager.java:50)
	at org.vertx.java.deploy.impl.VerticleManager$2.run(VerticleManager.java:291)
	at org.vertx.java.core.impl.Context$2.run(Context.java:119)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.processEventQueue(AbstractNioWorker.java:360)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:244)
	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:38)
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:102)
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
	at java.lang.Thread.run(Thread.java:722)
[New I/O  worker #3] 11:15:15,831 SEVERE [deployment-8c25d1bf-7714-4f01-b4a6-492fc66d542e-8]  Exception in Java verticle script
java.lang.NullPointerException
	at org.vertx.java.deploy.impl.VerticleManager.doUndeploy(VerticleManager.java:411)
	at org.vertx.java.deploy.impl.VerticleManager.doUndeploy(VerticleManager.java:400)
	at org.vertx.java.deploy.impl.VerticleManager.access$400(VerticleManager.java:50)
	at org.vertx.java.deploy.impl.VerticleManager$2.run(VerticleManager.java:291)
	at org.vertx.java.core.impl.Context$2.run(Context.java:119)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.processEventQueue(AbstractNioWorker.java:360)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:244)
	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:38)
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:102)
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
	at java.lang.Thread.run(Thread.java:722)
[New I/O  worker #2] 11:15:15,848 SEVERE [deployment-8c25d1bf-7714-4f01-b4a6-492fc66d542e-7]  Exception in Java verticle script
java.lang.NullPointerException
	at org.vertx.java.deploy.impl.VerticleManager.doUndeploy(VerticleManager.java:411)
	at org.vertx.java.deploy.impl.VerticleManager.doUndeploy(VerticleManager.java:400)
	at org.vertx.java.deploy.impl.VerticleManager.access$400(VerticleManager.java:50)
	at org.vertx.java.deploy.impl.VerticleManager$2.run(VerticleManager.java:291)
	at org.vertx.java.core.impl.Context$2.run(Context.java:119)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.processEventQueue(AbstractNioWorker.java:360)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:244)
	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:38)
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:102)
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
	at java.lang.Thread.run(Thread.java:722)
